[package]
name = "aoc2023"
version = "0.1.0"
authors = ["Henry Baba-Weiss <henry.babaweiss@gmail.com>"]
edition = "2021"

[dependencies]
itertools = "0.12.0"
rangemap = "1.4.0"
rayon = "1.8.0"
regex = "1.10.2"
